spring:
  application:
    name: Inventory_Management
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: inventory
    password: inventory

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

server:
  port: 8080

app:
  security:
    jwt:
      secret: change-me-in-prod
      expiration-seconds: 3600

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:inventory_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
